name: ❓ Question
description: Ask a question about SubMaker
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help!
        
        Before asking, please check:
        - [README](https://github.com/xtremexq/StremioSubMaker#readme) documentation
        - [Existing issues](https://github.com/xtremexq/StremioSubMaker/issues?q=is%3Aissue) for similar questions

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      options:
        - Configuration / Setup
        - Translation not working
        - Subtitles not appearing
        - API keys / Providers
        - Docker deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any relevant details about your setup or what you've already tried
