// Shared comprehensive language list used by translation tools
// Derived from fileUploadPageGenerator configuration
const allLanguages = [
    { code: 'ab', name: 'Abkhaz' },
    { code: 'ace', name: 'Acehnese' },
    { code: 'ach', name: 'Acholi' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'ak', name: 'Akan' },
    { code: 'sq', name: 'Albanian' },
    { code: 'alz', name: 'Alur' },
    { code: 'am', name: 'Amharic' },
    { code: 'ar', name: 'Arabic' },
    { code: 'ar-DZ', name: 'Arabic (Algeria)' },
    { code: 'ar-BH', name: 'Arabic (Bahrain)' },
    { code: 'ar-EG', name: 'Arabic (Egypt)' },
    { code: 'ar-IQ', name: 'Arabic (Iraq)' },
    { code: 'ar-JO', name: 'Arabic (Jordan)' },
    { code: 'ar-KW', name: 'Arabic (Kuwait)' },
    { code: 'ar-LB', name: 'Arabic (Lebanon)' },
    { code: 'ar-LY', name: 'Arabic (Libya)' },
    { code: 'ar-MA', name: 'Arabic (Morocco)' },
    { code: 'ar-OM', name: 'Arabic (Oman)' },
    { code: 'ar-QA', name: 'Arabic (Qatar)' },
    { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
    { code: 'ar-SY', name: 'Arabic (Syria)' },
    { code: 'ar-TN', name: 'Arabic (Tunisia)' },
    { code: 'ar-AE', name: 'Arabic (UAE)' },
    { code: 'ar-YE', name: 'Arabic (Yemen)' },
    { code: 'hy', name: 'Armenian' },
    { code: 'as', name: 'Assamese' },
    { code: 'awa', name: 'Awadhi' },
    { code: 'ay', name: 'Aymara' },
    { code: 'az', name: 'Azerbaijani' },
    { code: 'ban', name: 'Balinese' },
    { code: 'bm', name: 'Bambara' },
    { code: 'ba', name: 'Bashkir' },
    { code: 'eu', name: 'Basque' },
    { code: 'btx', name: 'Batak Karo' },
    { code: 'bts', name: 'Batak Simalungun' },
    { code: 'bbc', name: 'Batak Toba' },
    { code: 'be', name: 'Belarusian' },
    { code: 'bem', name: 'Bemba' },
    { code: 'bn', name: 'Bengali' },
    { code: 'bew', name: 'Betawi' },
    { code: 'bho', name: 'Bhojpuri' },
    { code: 'bik', name: 'Bikol' },
    { code: 'bs', name: 'Bosnian' },
    { code: 'bs-Cyrl', name: 'Bosnian (Cyrillic)' },
    { code: 'br', name: 'Breton' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'my', name: 'Burmese' },
    { code: 'bua', name: 'Buryat' },
    { code: 'yue', name: 'Cantonese' },
    { code: 'ca', name: 'Catalan' },
    { code: 'ceb', name: 'Cebuano' },
    { code: 'chr', name: 'Cherokee' },
    { code: 'hne', name: 'Chhattisgarhi' },
    { code: 'zh', name: 'Chinese' },
    { code: 'zh-CN', name: 'Chinese (Simplified)' },
    { code: 'zh-TW', name: 'Chinese (Traditional)' },
    { code: 'zh-HK', name: 'Chinese (Hong Kong)' },
    { code: 'zh-SG', name: 'Chinese (Singapore)' },
    { code: 'ctg', name: 'Chittagonian' },
    { code: 'cv', name: 'Chuvash' },
    { code: 'co', name: 'Corsican' },
    { code: 'crh', name: 'Crimean Tatar' },
    { code: 'hr', name: 'Croatian' },
    { code: 'cs', name: 'Czech' },
    { code: 'da', name: 'Danish' },
    { code: 'prs', name: 'Dari' },
    { code: 'dv', name: 'Dhivehi (Maldivian)' },
    { code: 'din', name: 'Dinka' },
    { code: 'doi', name: 'Dogri' },
    { code: 'dov', name: 'Dombe' },
    { code: 'nl', name: 'Dutch' },
    { code: 'nl-BE', name: 'Dutch (Belgium)' },
    { code: 'nl-NL', name: 'Dutch (Netherlands)' },
    { code: 'dyu', name: 'Dyula' },
    { code: 'dz', name: 'Dzongkha' },
    { code: 'en', name: 'English' },
    { code: 'en-AU', name: 'English (Australia)' },
    { code: 'en-CA', name: 'English (Canada)' },
    { code: 'en-IN', name: 'English (India)' },
    { code: 'en-IE', name: 'English (Ireland)' },
    { code: 'en-NZ', name: 'English (New Zealand)' },
    { code: 'en-PH', name: 'English (Philippines)' },
    { code: 'en-SG', name: 'English (Singapore)' },
    { code: 'en-ZA', name: 'English (South Africa)' },
    { code: 'en-GB', name: 'English (UK)' },
    { code: 'en-US', name: 'English (US)' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'et', name: 'Estonian' },
    { code: 'ee', name: 'Ewe' },
    { code: 'fo', name: 'Faroese' },
    { code: 'fj', name: 'Fijian' },
    { code: 'fil', name: 'Filipino' },
    { code: 'fi', name: 'Finnish' },
    { code: 'fr', name: 'French' },
    { code: 'fr-BE', name: 'French (Belgium)' },
    { code: 'fr-CA', name: 'French (Canada)' },
    { code: 'fr-FR', name: 'French (France)' },
    { code: 'fr-CH', name: 'French (Switzerland)' },
    { code: 'fy', name: 'Frisian' },
    { code: 'ff', name: 'Fulani (Fula)' },
    { code: 'gaa', name: 'Ga' },
    { code: 'gl', name: 'Galician' },
    { code: 'lg', name: 'Ganda (Luganda)' },
    { code: 'ka', name: 'Georgian' },
    { code: 'de', name: 'German' },
    { code: 'de-AT', name: 'German (Austria)' },
    { code: 'de-DE', name: 'German (Germany)' },
    { code: 'de-CH', name: 'German (Switzerland)' },
    { code: 'el', name: 'Greek' },
    { code: 'gn', name: 'Guarani' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'ht', name: 'Haitian Creole' },
    { code: 'cnh', name: 'Hakha Chin' },
    { code: 'hak', name: 'Hakka' },
    { code: 'bgc', name: 'Haryanvi' },
    { code: 'ha', name: 'Hausa' },
    { code: 'haw', name: 'Hawaiian' },
    { code: 'he', name: 'Hebrew' },
    { code: 'hil', name: 'Hiligaynon' },
    { code: 'hi', name: 'Hindi' },
    { code: 'hmn', name: 'Hmong' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'hrx', name: 'Hunsrik' },
    { code: 'is', name: 'Icelandic' },
    { code: 'ig', name: 'Igbo' },
    { code: 'ilo', name: 'Ilocano' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ga', name: 'Irish' },
    { code: 'it', name: 'Italian' },
    { code: 'it-IT', name: 'Italian (Italy)' },
    { code: 'it-CH', name: 'Italian (Switzerland)' },
    { code: 'ja', name: 'Japanese' },
    { code: 'jv', name: 'Javanese' },
    { code: 'kn', name: 'Kannada' },
    { code: 'pam', name: 'Kapampangan' },
    { code: 'kk', name: 'Kazakh' },
    { code: 'km', name: 'Khmer' },
    { code: 'cgg', name: 'Kiga' },
    { code: 'ki', name: 'Kikuyu' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'ktu', name: 'Kituba' },
    { code: 'gom', name: 'Konkani' },
    { code: 'ko', name: 'Korean' },
    { code: 'ko-KR', name: 'Korean (South Korea)' },
    { code: 'ko-KP', name: 'Korean (North Korea)' },
    { code: 'kri', name: 'Krio' },
    { code: 'ku', name: 'Kurdish' },
    { code: 'ckb', name: 'Kurdish (Sorani)' },
    { code: 'ky', name: 'Kyrgyz' },
    { code: 'lo', name: 'Lao' },
    { code: 'ltg', name: 'Latgalian' },
    { code: 'la', name: 'Latin' },
    { code: 'lv', name: 'Latvian' },
    { code: 'lij', name: 'Ligurian' },
    { code: 'li', name: 'Limburgish' },
    { code: 'ln', name: 'Lingala' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'lmo', name: 'Lombard' },
    { code: 'luo', name: 'Luo' },
    { code: 'lb', name: 'Luxembourgish' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'mag', name: 'Magahi' },
    { code: 'mai', name: 'Maithili' },
    { code: 'mak', name: 'Makassar' },
    { code: 'mg', name: 'Malagasy' },
    { code: 'ms', name: 'Malay' },
    { code: 'ms-Arab', name: 'Malay (Jawi)' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'mt', name: 'Maltese' },
    { code: 'mi', name: 'Maori' },
    { code: 'mr', name: 'Marathi' },
    { code: 'chm', name: 'Meadow Mari' },
    { code: 'mni-Mtei', name: 'Meitei (Manipuri)' },
    { code: 'cdo', name: 'Min Dong' },
    { code: 'nan', name: 'Min Nan (Hokkien)' },
    { code: 'min', name: 'Minang' },
    { code: 'lus', name: 'Mizo' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'nv', name: 'Navajo' },
    { code: 'new', name: 'Nepalbhasa (Newari)' },
    { code: 'ne', name: 'Nepali' },
    { code: 'nso', name: 'Northern Sotho (Sepedi)' },
    { code: 'no', name: 'Norwegian' },
    { code: 'nb', name: 'Norwegian (Bokmål)' },
    { code: 'nn', name: 'Norwegian (Nynorsk)' },
    { code: 'nus', name: 'Nuer' },
    { code: 'ny', name: 'Nyanja (Chichewa)' },
    { code: 'oc', name: 'Occitan' },
    { code: 'or', name: 'Odia (Oriya)' },
    { code: 'om', name: 'Oromo' },
    { code: 'os', name: 'Ossetian' },
    { code: 'pag', name: 'Pangasinan' },
    { code: 'pap', name: 'Papiamento' },
    { code: 'ps', name: 'Pashto' },
    { code: 'fa', name: 'Persian (Farsi)' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'pt-BR', name: 'Portuguese (Brazil)' },
    { code: 'pa', name: 'Punjabi' },
    { code: 'pa-Arab', name: 'Punjabi (Shahmukhi)' },
    { code: 'qu', name: 'Quechua' },
    { code: 'raj', name: 'Rajasthani' },
    { code: 'rom', name: 'Romani' },
    { code: 'ro', name: 'Romanian' },
    { code: 'ru', name: 'Russian' },
    { code: 'sm', name: 'Samoan' },
    { code: 'sg', name: 'Sango' },
    { code: 'sa', name: 'Sanskrit' },
    { code: 'gd', name: 'Scottish Gaelic' },
    { code: 'sr', name: 'Serbian' },
    { code: 'sr-Cyrl', name: 'Serbian (Cyrillic)' },
    { code: 'sr-Latn', name: 'Serbian (Latin)' },
    { code: 'st', name: 'Sesotho' },
    { code: 'crs', name: 'Seychellois Creole' },
    { code: 'shn', name: 'Shan' },
    { code: 'sn', name: 'Shona' },
    { code: 'scn', name: 'Sicilian' },
    { code: 'szl', name: 'Silesian' },
    { code: 'sd', name: 'Sindhi' },
    { code: 'si', name: 'Sinhala' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'so', name: 'Somali' },
    { code: 'nr', name: 'South Ndebele' },
    { code: 'es', name: 'Spanish' },
    { code: 'es-AR', name: 'Spanish (Argentina)' },
    { code: 'es-BO', name: 'Spanish (Bolivia)' },
    { code: 'es-CL', name: 'Spanish (Chile)' },
    { code: 'es-CO', name: 'Spanish (Colombia)' },
    { code: 'es-CR', name: 'Spanish (Costa Rica)' },
    { code: 'es-CU', name: 'Spanish (Cuba)' },
    { code: 'es-DO', name: 'Spanish (Dominican Republic)' },
    { code: 'es-EC', name: 'Spanish (Ecuador)' },
    { code: 'es-SV', name: 'Spanish (El Salvador)' },
    { code: 'es-GT', name: 'Spanish (Guatemala)' },
    { code: 'es-HN', name: 'Spanish (Honduras)' },
    { code: 'es-MX', name: 'Spanish (Mexico)' },
    { code: 'es-NI', name: 'Spanish (Nicaragua)' },
    { code: 'es-PA', name: 'Spanish (Panama)' },
    { code: 'es-PY', name: 'Spanish (Paraguay)' },
    { code: 'es-PE', name: 'Spanish (Peru)' },
    { code: 'es-PR', name: 'Spanish (Puerto Rico)' },
    { code: 'es-ES', name: 'Spanish (Spain)' },
    { code: 'es-UY', name: 'Spanish (Uruguay)' },
    { code: 'es-VE', name: 'Spanish (Venezuela)' },
    { code: 'suk', name: 'Sukuma' },
    { code: 'su', name: 'Sundanese' },
    { code: 'sw', name: 'Swahili' },
    { code: 'ss', name: 'Swati' },
    { code: 'sv', name: 'Swedish' },
    { code: 'sv-FI', name: 'Swedish (Finland)' },
    { code: 'sv-SE', name: 'Swedish (Sweden)' },
    { code: 'syl', name: 'Sylheti' },
    { code: 'tl', name: 'Tagalog' },
    { code: 'tg', name: 'Tajik' },
    { code: 'zgh', name: 'Tamazight (Tifinagh)' },
    { code: 'ta', name: 'Tamil' },
    { code: 'tt', name: 'Tatar' },
    { code: 'te', name: 'Telugu' },
    { code: 'tet', name: 'Tetum' },
    { code: 'th', name: 'Thai' },
    { code: 'bo', name: 'Tibetan' },
    { code: 'ti', name: 'Tigrinya' },
    { code: 'ts', name: 'Tsonga' },
    { code: 'tn', name: 'Tswana' },
    { code: 'tr', name: 'Turkish' },
    { code: 'tk', name: 'Turkmen' },
    { code: 'tw', name: 'Twi' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'ur', name: 'Urdu' },
    { code: 'ug', name: 'Uyghur' },
    { code: 'uz', name: 'Uzbek' },
    { code: 've', name: 'Venda' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'cy', name: 'Welsh' },
    { code: 'wo', name: 'Wolof' },
    { code: 'wuu', name: 'Wu (Shanghainese)' },
    { code: 'xh', name: 'Xhosa' },
    { code: 'yi', name: 'Yiddish' },
    { code: 'yo', name: 'Yoruba' },
    { code: 'yua', name: 'Yucatec Maya' },
    { code: 'zu', name: 'Zulu' },

    // ── Extended languages (rare, ancient, regional, constructed) ──
    // Only shown when user enables "Extended languages list" checkbox
    { code: 'akk', name: 'Akkadian', extended: true },
    { code: 'ady', name: 'Adyghe', extended: true },
    { code: 'ain', name: 'Ainu', extended: true },
    { code: 'ang', name: 'Old English', extended: true },
    { code: 'arc', name: 'Aramaic', extended: true },
    { code: 'arn', name: 'Mapudungun', extended: true },
    { code: 'bal', name: 'Baluchi', extended: true },
    { code: 'bci', name: 'Baoulé', extended: true },
    { code: 'bcl', name: 'Central Bikol', extended: true },
    { code: 'bpy', name: 'Bishnupriya', extended: true },
    { code: 'brx', name: 'Bodo', extended: true },
    { code: 'chk', name: 'Chuukese', extended: true },
    { code: 'cic', name: 'Chickasaw', extended: true },
    { code: 'cop', name: 'Coptic', extended: true },
    { code: 'csb', name: 'Kashubian', extended: true },
    { code: 'dsb', name: 'Lower Sorbian', extended: true },
    { code: 'efi', name: 'Efik', extended: true },
    { code: 'egl', name: 'Emilian', extended: true },
    { code: 'egy', name: 'Ancient Egyptian', extended: true },
    { code: 'enm', name: 'Middle English', extended: true },
    { code: 'fan', name: 'Fang', extended: true },
    { code: 'fro', name: 'Old French', extended: true },
    { code: 'fuc', name: 'Pulaar', extended: true },
    { code: 'fur', name: 'Friulian', extended: true },
    { code: 'gcr', name: 'Guianese Creole', extended: true },
    { code: 'gez', name: "Ge'ez", extended: true },
    { code: 'gil', name: 'Gilbertese (Kiribati)', extended: true },
    { code: 'glk', name: 'Gilaki', extended: true },
    { code: 'gmh', name: 'Middle High German', extended: true },
    { code: 'got', name: 'Gothic', extended: true },
    { code: 'grc', name: 'Ancient Greek', extended: true },
    { code: 'haz', name: 'Hazaragi', extended: true },
    { code: 'hbo', name: 'Ancient Hebrew', extended: true },
    { code: 'hit', name: 'Hittite', extended: true },
    { code: 'hsb', name: 'Upper Sorbian', extended: true },
    { code: 'ike', name: 'Eastern Canadian Inuktitut', extended: true },
    { code: 'jam', name: 'Jamaican Patois', extended: true },
    { code: 'jbo', name: 'Lojban', extended: true },
    { code: 'kas', name: 'Kashmiri', extended: true },
    { code: 'kbd', name: 'Kabardian', extended: true },
    { code: 'kha', name: 'Khasi', extended: true },
    { code: 'kmb', name: 'Kimbundu', extended: true },
    { code: 'kmr', name: 'Kurdish (Kurmanji)', extended: true },
    { code: 'kok', name: 'Kokborok', extended: true },
    { code: 'lez', name: 'Lezgian', extended: true },
    { code: 'lfn', name: 'Lingua Franca Nova', extended: true },
    { code: 'loz', name: 'Lozi', extended: true },
    { code: 'lrc', name: 'Luri', extended: true },
    { code: 'lua', name: 'Luba-Lulua', extended: true },
    { code: 'lzh', name: 'Classical Chinese', extended: true },
    { code: 'mdh', name: 'Maguindanaon', extended: true },
    { code: 'mfe', name: 'Mauritian Creole', extended: true },
    { code: 'mic', name: "Mi'kmaq", extended: true },
    { code: 'mnk', name: 'Mandinka', extended: true },
    { code: 'mos', name: 'Mossi (Mooré)', extended: true },
    { code: 'msb', name: 'Masbateño', extended: true },
    { code: 'mwr', name: 'Marwadi', extended: true },
    { code: 'myn', name: "Maya (K'iche')", extended: true },
    { code: 'nah', name: 'Nahuatl', extended: true },
    { code: 'nap', name: 'Neapolitan', extended: true },
    { code: 'nci', name: 'Classical Nahuatl', extended: true },
    { code: 'niu', name: 'Niuean', extended: true },
    { code: 'non', name: 'Old Norse', extended: true },
    { code: 'nov', name: 'Novial', extended: true },
    { code: 'npi', name: 'Nepali (specific)', extended: true },
    { code: 'nyn', name: 'Nyankole', extended: true },
    { code: 'odt', name: 'Old Dutch', extended: true },
    { code: 'pal', name: 'Middle Persian (Pahlavi)', extended: true },
    { code: 'pau', name: 'Palauan', extended: true },
    { code: 'peo', name: 'Old Persian', extended: true },
    { code: 'phn', name: 'Phoenician', extended: true },
    { code: 'pms', name: 'Piedmontese', extended: true },
    { code: 'pon', name: 'Pohnpeian', extended: true },
    { code: 'prg', name: 'Old Prussian', extended: true },
    { code: 'qya', name: 'Quenya (Tolkien)', extended: true },
    { code: 'rar', name: 'Rarotongan', extended: true },
    { code: 'rup', name: 'Aromanian', extended: true },
    { code: 'sgs', name: 'Samogitian', extended: true },
    { code: 'sjn', name: 'Sindarin (Tolkien)', extended: true },
    { code: 'snk', name: 'Soninke', extended: true },
    { code: 'srn', name: 'Sranan Tongo', extended: true },
    { code: 'sus', name: 'Susu', extended: true },
    { code: 'sux', name: 'Sumerian', extended: true },
    { code: 'swb', name: 'Comorian', extended: true },
    { code: 'syc', name: 'Classical Syriac', extended: true },
    { code: 'tcy', name: 'Tulu', extended: true },
    { code: 'tiv', name: 'Tiv', extended: true },
    { code: 'tkl', name: 'Tokelauan', extended: true },
    { code: 'tpi', name: 'Tok Pisin', extended: true },
    { code: 'tsg', name: 'Tausug', extended: true },
    { code: 'tum', name: 'Tumbuka', extended: true },
    { code: 'tvl', name: 'Tuvaluan', extended: true },
    { code: 'tzl', name: 'Talossan', extended: true },
    { code: 'umb', name: 'Umbundu', extended: true },
    { code: 'vec', name: 'Venetian', extended: true },
    { code: 'war', name: 'Waray', extended: true },
    { code: 'wls', name: 'Wallisian', extended: true },
    { code: 'yrl', name: 'Nheengatu', extended: true },
    { code: 'zap', name: 'Zapotec', extended: true },
    { code: 'zza', name: 'Zaza', extended: true }
];

module.exports = { allLanguages };
